repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - name: All executables should be shebang scripts
        id: check-executables-have-shebangs
      - name: All shebang scripts should be executable
        id: check-shebang-scripts-are-executable
      - name: All non-empty files should end with a newline
        id: end-of-file-fixer
      - name: No files should have trailing whitespaces
        id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - name: Format Rust files
        id: fmt

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - name: Format Markdown files
        id: mdformat
        additional_dependencies:
          - mdformat-rustfmt
          - mdformat-shfmt
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-tables
        files: \.md$

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - name: Format YAML files
        id: prettier
        files: \.(yaml|yml)$

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - name: Format TOML files
        id: taplo-format

  - repo: local
    hooks:
      - name: Run `cargo clippy`
        id: clippy
        description: Lint rust sources
        entry: cargo
        args:
          - clippy
          - --all-targets
          - --all-features
          - --
          - -D
          - warnings
          - -D
          - clippy::all
          - -D
          - clippy::pedantic
          - -D
          - clippy::nursery
          - -D
          - clippy::cargo
        language: system
        types: [rust]
        pass_filenames: false
