name: CI

on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/tmp
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: ${{ runner.os }}-rustup

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-pre-commit-4.2.0
          restore-keys: ${{ runner.os }}-pip

      - name: Cache pre-commit downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-pre-commit

      - name: Cache Cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/registry
            ${{ env.CARGO_HOME }}/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          # When upgrading pre-commit, make sure to update the key in the cache key.
          pip install pre-commit==4.2.0

      - name: Install pre-commit dependencies
        run: |
          cargo install cargo-audit@0.21.2 cargo-features-manager@0.10.0 taplo-cli@0.9.3

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Run tests
        timeout-minutes: 1
        run: cargo test
