name: CI

on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-pre-commit-4.2.0
          restore-keys: ${{ runner.os }}-pip-

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          # When upgrading pre-commit, make sure to update the key in the cache key.
          pip install pre-commit==4.2.0

      - name: Cache pre-commit downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Cache Cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CARGO_HOME }}/registry
            ${{ env.CARGO_HOME }}/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Run tests
        timeout-minutes: 1
        run: cargo test
